name:BuildandDeployFlask(GHCR)

on:
push:
branches:
-main

permissions:
contents:read
packages:write# OBRIGATÓRIO para GHCR

jobs:
build:
runs-on:ubuntu-latest

steps:
-name:Checkoutdocódigo
uses:actions/checkout@v4

-name:LoginnoGitHubContainerRegistry
uses:docker/login-action@v3
with:
registry:ghcr.io
username:${{github.actor}}
password:${{secrets.GITHUB_TOKEN}}

-name:Buildepushdaimagem
uses:docker/build-push-action@v5
with:
push:true
tags:ghcr.io/${{github.repository}}:latest

